export const DataComponent = {
  cardDataHome: [
    [
      {
        img: "handshake-o",
        navigateRoute: "Home",
        nameLabel: "Clientes",
        size: 30,
      },
      { img: "shopping-cart", navigateRoute: "Stock", nameLabel: "Estoque" },
      { img: "barcode", navigateRoute: "Home", nameLabel: "Vendas", size: 35 },
    ],
    [
      {
        img: "line-chart",
        navigateRoute: "Lucros",
        nameLabel: "Lucros",
        size: 30,
      },
      { img: "cart-arrow-down", navigateRoute: "Home", nameLabel: "Prejuízos" },
      {
        img: "pie-chart",
        navigateRoute: "Home",
        nameLabel: "Relatórios",
        size: 32,
      },
    ],
  ],
  stockData: [
    {"productId": 1, "name": "Biscoito de Milho", "qtd": 100},
    {"productId": 2, "name": "Bolacha de água e sal", "qtd": 150},
    {"productId": 3, "name": "Biscoito de chocolate", "qtd": 120},
    {"productId": 4, "name": "Biscoito recheado de morango", "qtd": 90},
    {"productId": 5, "name": "Cookies de aveia", "qtd": 80},
    {"productId": 6, "name": "Biscoito integral de mel", "qtd": 110},
    {"productId": 7, "name": "Wafers de baunilha", "qtd": 130},
    {"productId": 8, "name": "Biscoito de manteiga", "qtd": 100},
    {"productId": 9, "name": "Biscoito amanteigado de limão", "qtd": 70},
    {"productId": 10, "name": "Bolacha recheada de chocolate", "qtd": 95},
    {"productId": 11, "name": "Biscoito de polvilho", "qtd": 200},
    {"productId": 12, "name": "Biscoito de nata", "qtd": 85},
    {"productId": 13, "name": "Bolacha de chocolate branco", "qtd": 60},
    {"productId": 14, "name": "Biscoito de coco", "qtd": 140},
    {"productId": 15, "name": "Biscoito de gengibre", "qtd": 50},
    {"productId": 16, "name": "Bolacha maria", "qtd": 180},
    {"productId": 17, "name": "Biscoito salgado de queijo", "qtd": 160},
    {"productId": 18, "name": "Biscoito de leite maltado", "qtd": 75},
    {"productId": 19, "name": "Wafers de chocolate", "qtd": 130},
    {"productId": 20, "name": "Biscoito de amendoim", "qtd": 65},
    {"productId": 21, "name": "Bolacha de manteiga escocesa", "qtd": 55},
    {"productId": 22, "name": "Biscoito de canela", "qtd": 85},
    {"productId": 23, "name": "Biscoito de baunilha", "qtd": 95},
    {"productId": 24, "name": "Bolacha de mel", "qtd": 105},
    {"productId": 25, "name": "Biscoito de café", "qtd": 120},
    {"productId": 26, "name": "Bolacha de creme", "qtd": 90},
    {"productId": 27, "name": "Biscoito de laranja", "qtd": 110},
    {"productId": 28, "name": "Bolacha de morango", "qtd": 100},
    {"productId": 29, "name": "Biscoito de aveia e chocolate", "qtd": 80},
    {"productId": 30, "name": "Bolacha de limão", "qtd": 70},
    {"productId": 31, "name": "Biscoito de manteiga de amendoim", "qtd": 130},
    {"productId": 32, "name": "Bolacha de noz", "qtd": 60},
    {"productId": 33, "name": "Biscoito de especiarias", "qtd": 140},
    {"productId": 34, "name": "Bolacha de amêndoa", "qtd": 150},
    {"productId": 35, "name": "Biscoito de queijo parmesão", "qtd": 95},
    {"productId": 36, "name": "Bolacha de avelã", "qtd": 85},
    {"productId": 37, "name": "Biscoito de chocolate amargo", "qtd": 75},
    {"productId": 38, "name": "Bolacha de iogurte", "qtd": 65},
    {"productId": 39, "name": "Biscoito de chocolate branco", "qtd": 55},
    {"productId": 40, "name": "Bolacha de café", "qtd": 45},
    {"productId": 41, "name": "Biscoito de caramelo", "qtd": 135},
    {"productId": 42, "name": "Bolacha de castanha", "qtd": 125},
    {"productId": 43, "name": "Biscoito de frutas vermelhas", "qtd": 115},
    {"productId": 44, "name": "Bolacha de gergelim", "qtd": 105},
    {"productId": 45, "name": "Biscoito de menta", "qtd": 95},
    {"productId": 46, "name": "Bolacha de chocolate com menta", "qtd": 85},
  ]
};
